name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Adjust the Node.js version as needed

    - name: Install dependencies
      run: npm install

    - name: Start Express.js Server
      run: npm start  # Use the appropriate start command for your server

    - name: Wait for Server to Start
      run: |
        while [ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:3000)" != "200" ]; do sleep 1; done

    - name: Run Tests
      run: npm test  # Replace with your actual test command
      
